version: '3.8'

services:

  php:
    build:
      context: ./php
    networks:
      - mediawiki-network

    volumes:
      - "mediawiki-volume-${MVF}:/app"

networks:
  mediawiki-network:

volumes:
  mediawiki-volume-${MVF}:
