#version: '3.8'

services:

  data:
    container_name: "${NAME}-data-${MVF}"
    image:          "${NAME}-data:${MVF}"
    build:
      context: ./data
      args:
        MVS:  ${MVS}
        MVF:  ${MVF}
        MEXT: ${MEXT}
    networks:
      - "mediawiki-network"
    volumes:
      - "volume-${MVF}:/app"

networks:
  mediawiki-network:

volumes:
  volume-${MVF}:
