#version: '3.8'

services:

  data:
    container_name: "${NAME}-data-${MVF}"
    build:
      context: ./data
      args:
        MVS: ${MVS}
        MVF: ${MVF}
    networks:
      - "mediawiki-network"
    volumes:
      - "volume-${MVF}:/app"

  memcached:
    container_name: "${NAME}-memcached-${MVF}"
    build:
      context: ./memcached
    networks:
      - "mediawiki-network"

  mariadb:
    container_name: "${NAME}-mariadb-${MVF}"
    build:
      context: ./mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    networks:
      - "mediawiki-network"

  php:
    container_name: "${NAME}-php-${MVF}"
    build:
      context: ./php
    depends_on:
      - data
      - memcached
      - mariadb
    networks:
      - "mediawiki-network"
    volumes:
      - "volume-${MVF}:/app"

  nginx:
    container_name: "${NAME}-nginx-${MVF}"
    build:
      context: ./nginx
    ports:
      - "${PORT}:80"
    networks:
      - "mediawiki-network"
    volumes:
      - "volume-${MVF}:/app"
    depends_on:
      - data
      - php

networks:
  mediawiki-network:

volumes:
  volume-${MVF}:
