version: '3.8'

services:

  data:
    build:
      context: ./data
    networks:
      - mediawiki-network
    volumes:
      - mediawiki-data:/app

  memcached:
    build:
      context: ./memcached
    networks:
      - mediawiki-network

  mariadb:
    build:
      context: ./mariadb
    networks:
      - mediawiki-network

  php:
    build:
      context: ./php
    depends_on:
      - data
      - memcached
      - mariadb
    networks:
      - mediawiki-network
    volumes:
      - mediawiki-data:/app

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - mediawiki-network
    volumes:
      - mediawiki-data:/app
    depends_on:
      - data
      - php

networks:
  mediawiki-network:

volumes:
  mediawiki-data:
