version: '3.8'

services:

  data:
    container_name: "mediawiki-data-${MVF}"
    build:
      context: ./data
      args:
        MVS: ${MVS}
        MVF: ${MVF}

    networks:
      - mediawiki-network
    volumes:
      - "mediawiki-volume-${MVF}:/app"

  memcached:
    container_name: "mediawiki-memcached-${MVF}"
    build:
      context: ./memcached
    networks:
      - mediawiki-network

  mariadb:
    container_name: "mediawiki-mariadb-${MVF}"
    build:
      context: ./mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes

    networks:
      - mediawiki-network

  php:
    container_name: "mediawiki-php-${MVF}"
    build:
      context: ./php
    depends_on:
      - data
      - memcached
      - mariadb
    networks:
      - mediawiki-network

    volumes:
      - "mediawiki-volume-${MVF}:/app"

  nginx:
    container_name: "mediawiki-nginx-${MVF}"
    build:
      context: ./nginx
    ports:
      - "8081:80"
    networks:
      - mediawiki-network
    volumes:
      - "mediawiki-volume-${MVF}:/app"
    depends_on:
      - data
      - php

networks:
  mediawiki-network:

volumes:
  mediawiki-volume-${MVF}:
