version: '3.8'

services:
  memcached:
    build:
      context: ./memcached
    networks:
      - mediawiki-network

  mariadb:
    build:
      context: ./mariadb
    networks:
      - mediawiki-network

  php:
    build:
      context: ./php
    depends_on:
      - memcached
      - mariadb
    networks:
      - mediawiki-network
    volumes:
      - /app:/app

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - mediawiki-network
    volumes:
      - /app:/app
    depends_on:
      - php

networks:
  mediawiki-network:

volumes:
  mediawiki-data: