services:

  ollama-bat:
    image: docker.io/alpine/ollama
    container_name: ollama-bat
    restart: unless-stopped

  ollama-bi:
    image: docker.io/alpine/ollama
    container_name: ollama-bi
    restart: unless-stopped

  caddy:
    build: .
    container_name: ollama-caddy
    restart: unless-stopped
    ports:
      - "11434:11434"
    depends_on:
      - ollama-bat
      - ollama-bi
