services:

  ollama-01:
    image: docker.io/alpine/ollama
    container_name: ollama-01
    restart: unless-stopped
    volumes:
      - ./models:/root/.ollama/models

  ollama-02:
    image: docker.io/alpine/ollama
    container_name: ollama-02
    restart: unless-stopped
    volumes:
      - ./models:/root/.ollama/models

  caddy:
    build: .
    container_name: ollama-caddy
    restart: unless-stopped
    ports:
      - "11434:11434"
    depends_on:
      - ollama-01
      - ollama-02

volumes:
  ollama-models:
